# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Hash-Merge
version:      0.10
version_from: Merge.pm
installdirs:  site
requires:
    Clone:                         0
    Test::More:                    0.33

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
