---
abstract: 'Simple and fast captcha'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  lib::abs: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Captcha-Easy
no_index:
  directory:
    - inc
    - t
provides:
  Captcha::Easy:
    file: lib/Captcha/Easy.pm
    version: 0.03
requires:
  Digest::SHA1: 0
  File::Find: 0
  Imager: 0
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
