---
abstract: 'Perl pragma to declare previously undeclared constants'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  lib::abs: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: constant-def
no_index:
  directory:
    - inc
    - t
provides:
  constant::abs:
    file: lib/constant/abs.pm
    version: 0.02
  constant::def:
    file: lib/constant/def.pm
    version: 0.02
requires:
  constant: 1.05
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
