---
abstract: 'Perl pragma to declare previously undeclared constants'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  Test::More: 0
  ex::lib: 0.03
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: constant-def
no_index:
  directory:
    - inc
    - t
requires:
  constant: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
