---
abstract: 'Parse xml to simple tree'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  Test::More: 0
  ex::lib: 0
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Parser-Style-EasyTree
no_index:
  directory:
    - inc
    - t
requires:
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
